name: Allegory
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7091be'
    - '#000000'
    - '#d2d2d2'
    - '#3f3f3f'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
