name: Allegory
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#80afdb'
    - '#1f1b0f'
    - '#6a8eb0'
    - '#433f56'
    - '#9fd4fb'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
