name: Allegory
favicon: null
layout_spectrum: 0.8843829352408648
typography_spectrum: 0.5083696797955781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.9510643943212926
  lightness: 0.5678262489382178
  saturation: 0.15212268312461674
  rhythmicContrast: 0.7872943705879152
purpose: []
