name: Allegory
favicon: null
layout_spectrum: 0.79356
typography_spectrum: 0.27709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b2b2b2'
    - '#2a2a2a'
    - '#8e8e8e'
    - '#5c5c5c'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
