name: Allegory
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6c5e2'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
