typography_spectrum: 0.2526297706644982
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.8413484375923872
  lightness: 0.413679062621668
  saturation: 0.6253222245723009
  rhythmicContrast: 0.6412400645203888
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3968421828467399
analytics:
  google: null
  facebook: null
  twitter: null
name: Allegory
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Alegoría
description: intersección de ideas
purpose: []
