name: Allegory
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1a18'
    - '#783637'
    - '#d7d8dc'
    - '#525542'
    - '#c2a190'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
