name: Allegory
favicon: null
layout_spectrum: 0.92114
typography_spectrum: 0.27709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#fc9b00'
    - '#fcfefe'
    - '#6b5d60'
    - '#38b9b8'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
